repo:
    - ./*

ci:
    - any: ['.github/**/*']

test:
    - src/**/*.test.ts

"domain/sdk":
    - packages/platform-sdk/*
    - packages/platform-sdk/**/*

"domain/ada":
    - packages/platform-sdk-ada/*
    - packages/platform-sdk-ada/**/*

"domain/ark":
    - packages/platform-sdk-ark/*
    - packages/platform-sdk-ark/**/*

"domain/atom":
    - packages/platform-sdk-atom/*
    - packages/platform-sdk-atom/**/*

"domain/avax":
    - packages/platform-sdk-avax/*
    - packages/platform-sdk-avax/**/*

"domain/btc":
    - packages/platform-sdk-btc/*
    - packages/platform-sdk-btc/**/*

"domain/btc/indexer":
    - packages/platform-sdk-btc-indexer/*
    - packages/platform-sdk-btc-indexer/**/*

"domain/btc/server":
    - packages/platform-sdk-btc-server/*
    - packages/platform-sdk-btc-server/**/*

"domain/cli":
    - packages/platform-sdk-cli/*
    - packages/platform-sdk-cli/**/*

"domain/coincap":
    - packages/platform-sdk-coincap/*
    - packages/platform-sdk-coincap/**/*

"domain/coingecko":
    - packages/platform-sdk-coingecko/*
    - packages/platform-sdk-coingecko/**/*

"domain/crypto":
    - packages/platform-sdk-crypto/*
    - packages/platform-sdk-crypto/**/*

"domain/cryptocompare":
    - packages/platform-sdk-cryptocompare/*
    - packages/platform-sdk-cryptocompare/**/*

"domain/dot":
    - packages/platform-sdk-dot/*
    - packages/platform-sdk-dot/**/*

"domain/dot/indexer":
    - packages/platform-sdk-dot-indexer/*
    - packages/platform-sdk-dot-indexer/**/*

"domain/egld":
    - packages/platform-sdk-egld/*
    - packages/platform-sdk-egld/**/*

"domain/eos":
    - packages/platform-sdk-eos/*
    - packages/platform-sdk-eos/**/*

"domain/eth":
    - packages/platform-sdk-eth/*
    - packages/platform-sdk-eth/**/*

"domain/eth/indexer":
    - packages/platform-sdk-eth-indexer/*
    - packages/platform-sdk-eth-indexer/**/*

"domain/eth/server":
    - packages/platform-sdk-eth-server/*
    - packages/platform-sdk-eth-server/**/*

"domain/http/axios":
    - packages/platform-sdk-http-axios/*
    - packages/platform-sdk-http-axios/**/*

"domain/http/bent":
    - packages/platform-sdk-http-bent/*
    - packages/platform-sdk-http-bent/**/*

"domain/http/got":
    - packages/platform-sdk-http-got/*
    - packages/platform-sdk-http-got/**/*

"domain/http/ky":
    - packages/platform-sdk-http-ky/*
    - packages/platform-sdk-http-ky/**/*

"domain/http/node-fetch":
    - packages/platform-sdk-http-node-fetch/*
    - packages/platform-sdk-http-node-fetch/**/*

"domain/intl":
    - packages/platform-sdk-intl/*
    - packages/platform-sdk-intl/**/*

"domain/lsk":
    - packages/platform-sdk-lsk/*
    - packages/platform-sdk-lsk/**/*

"domain/markets":
    - packages/platform-sdk-markets/*
    - packages/platform-sdk-markets/**/*

"domain/neo":
    - packages/platform-sdk-neo/*
    - packages/platform-sdk-neo/**/*

"domain/news":
    - packages/platform-sdk-news/*
    - packages/platform-sdk-news/**/*

"domain/profiles":
    - packages/platform-sdk-profiles/*
    - packages/platform-sdk-profiles/**/*

"domain/sol":
    - packages/platform-sdk-sol/*
    - packages/platform-sdk-sol/**/*

"domain/support":
    - packages/platform-sdk-support/*
    - packages/platform-sdk-support/**/*

"domain/trx":
    - packages/platform-sdk-trx/*
    - packages/platform-sdk-trx/**/*

"domain/xlm":
    - packages/platform-sdk-xlm/*
    - packages/platform-sdk-xlm/**/*

"domain/xrp":
    - packages/platform-sdk-xrp/*
    - packages/platform-sdk-xrp/**/*
