packageExtensions:
  "@elrondnetwork/elrond-core-js@*":
    dependencies:
      "@babel/runtime": "*"
  "@polkadot/util@*":
    dependencies:
      "@polkadot/x-global": "*"
  "@polkadot/wasm-crypto@*":
    dependencies:
      "@polkadot/x-randomvalues": "*"
  eosjs@*:
    dependencies:
      bn.js: 4.11.6

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-2.4.0.cjs
