# @TODO: once a package reaches 100% coverage it should be uncommented
ignore:
  - "platform-sdk-ada"
  - "platform-sdk-ark"
  - "platform-sdk-atom"
  - "platform-sdk-btc"
  - "platform-sdk-eos"
  - "platform-sdk-eth"
  - "platform-sdk-json-rpc"
  - "platform-sdk-lsk"
  - "platform-sdk-neo"
  - "platform-sdk-trx"
  - "platform-sdk-xlm"
  - "platform-sdk-xmr"
  - "platform-sdk-xrp"
