name: CI

on:
    push:
        branches:
            - "master"
            - "develop"
    pull_request:
        types: [ready_for_review, synchronize, opened]

jobs:
    conflicts:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}

            - name: Merge Conflict finder
              uses: olivernybroe/action-conflict-finder@v1.1

    unit:
        needs: [conflicts]

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install
              run: yarn install --immutable --immutable-cache

            - name: Build
              run: yarn run build

            - name: Test
              run: |
                  jest packages/platform-sdk/ --coverage
                  jest packages/platform-sdk-ada/ --coverage
                  jest packages/platform-sdk-ark/ --coverage
                  jest packages/platform-sdk-atom/ --coverage
                  jest packages/platform-sdk-btc/ --coverage
                  jest packages/platform-sdk-coincap/ --coverage
                  jest packages/platform-sdk-coingecko/ --coverage
                  jest packages/platform-sdk-crypto/ --coverage
                  jest packages/platform-sdk-cryptocompare/ --coverage
                  jest packages/platform-sdk-eos/ --coverage
                  jest packages/platform-sdk-eth/ --coverage
                  jest packages/platform-sdk-http-axios/ --coverage
                  jest packages/platform-sdk-http-bent/ --coverage
                  jest packages/platform-sdk-http-got/ --coverage
                  jest packages/platform-sdk-http-ky/ --coverage
                  jest packages/platform-sdk-http-node-fetch/ --coverage
                  jest packages/platform-sdk-intl/ --coverage
                  jest packages/platform-sdk-lsk/ --coverage
                  jest packages/platform-sdk-markets/ --coverage
                  jest packages/platform-sdk-neo/ --coverage
                  jest packages/platform-sdk-news/ --coverage
                  jest packages/platform-sdk-profiles/ --coverage
                  jest packages/platform-sdk-support/ --coverage
                  jest packages/platform-sdk-trx/ --coverage
                  jest packages/platform-sdk-xlm/ --coverage
                  jest packages/platform-sdk-xrp/ --coverage
