name: CI

on:
    push:
        branches:
            - "master"
            - "develop"
    pull_request:
        types: [ready_for_review, synchronize, opened]

jobs:
    conflicts:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}

            - name: Merge Conflict finder
              uses: olivernybroe/action-conflict-finder@v1.1

    unit:
        needs: [conflicts]

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install
              run: yarn install --immutable --immutable-cache

            - name: Build
              run: yarn run build

            - name: Test
              run: |
                  jest packages/platform-sdk/ --ci --maxWorkers=4
                  jest packages/platform-sdk-ada/ --ci --maxWorkers=4
                  jest packages/platform-sdk-ark/ --ci --maxWorkers=4
                  jest packages/platform-sdk-atom/ --ci --maxWorkers=4
                  jest packages/platform-sdk-btc/ --ci --maxWorkers=4
                  jest packages/platform-sdk-coincap/ --ci --maxWorkers=4
                  jest packages/platform-sdk-coingecko/ --ci --maxWorkers=4
                  jest packages/platform-sdk-crypto/ --ci --maxWorkers=4
                  jest packages/platform-sdk-cryptocompare/ --ci --maxWorkers=4
                  jest packages/platform-sdk-eos/ --ci --maxWorkers=4
                  jest packages/platform-sdk-eth/ --ci --maxWorkers=4
                  jest packages/platform-sdk-http-axios/ --ci --maxWorkers=4
                  jest packages/platform-sdk-http-bent/ --ci --maxWorkers=4
                  jest packages/platform-sdk-http-got/ --ci --maxWorkers=4
                  jest packages/platform-sdk-http-ky/ --ci --maxWorkers=4
                  jest packages/platform-sdk-http-node-fetch/ --ci --maxWorkers=4
                  jest packages/platform-sdk-intl/ --ci --maxWorkers=4
                  jest packages/platform-sdk-lsk/ --ci --maxWorkers=4
                  jest packages/platform-sdk-markets/ --ci --maxWorkers=4
                  jest packages/platform-sdk-neo/ --ci --maxWorkers=4
                  jest packages/platform-sdk-news/ --ci --maxWorkers=4
                  jest packages/platform-sdk-profiles/ --ci --maxWorkers=4
                  jest packages/platform-sdk-support/ --ci --maxWorkers=4
                  jest packages/platform-sdk-trx/ --ci --maxWorkers=4
                  jest packages/platform-sdk-xlm/ --ci --maxWorkers=4
                  jest packages/platform-sdk-xrp/ --ci --maxWorkers=4
