name: CI

on:
    push:
        branches:
            - "master"
            - "develop"
    pull_request:
        types: [ready_for_review, synchronize, opened]

jobs:
    conflicts:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}

            - name: Merge Conflict finder
              uses: olivernybroe/action-conflict-finder@v1.1

    sdk:
        needs: [conflicts]

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install
              run: yarn install --immutable --immutable-cache

            - name: Build
              run: yarn run build

            - name: Test
              run: cd packages/platform-sdk/ && yarn run test --coverage

    ada:
        needs: [conflicts]

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install
              run: yarn install --immutable --immutable-cache

            - name: Build
              run: yarn run build

            - name: Test
              run: cd packages/platform-sdk-ada/ && yarn run test --coverage

    ark:
        needs: [conflicts]

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install
              run: yarn install --immutable --immutable-cache

            - name: Build
              run: yarn run build

            - name: Test
              run: cd packages/platform-sdk-ark/ && yarn run test --coverage

    atom:
        needs: [conflicts]

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install
              run: yarn install --immutable --immutable-cache

            - name: Build
              run: yarn run build

            - name: Test
              run: cd packages/platform-sdk-atom/ && yarn run test --coverage

    btc:
        needs: [conflicts]

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install
              run: yarn install --immutable --immutable-cache

            - name: Build
              run: yarn run build

            - name: Test
              run: cd packages/platform-sdk-btc/ && yarn run test --coverage

    coincap:
        needs: [conflicts]

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install
              run: yarn install --immutable --immutable-cache

            - name: Build
              run: yarn run build

            - name: Test
              run: cd packages/platform-sdk-coincap/ && yarn run test --coverage

    coingecko:
        needs: [conflicts]

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install
              run: yarn install --immutable --immutable-cache

            - name: Build
              run: yarn run build

            - name: Test
              run: cd packages/platform-sdk-coingecko/ && yarn run test --coverage

    crypto:
        needs: [conflicts]

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install
              run: yarn install --immutable --immutable-cache

            - name: Build
              run: yarn run build

            - name: Test
              run: cd packages/platform-sdk-crypto/ && yarn run test --coverage

    cryptocompare:
        needs: [conflicts]

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install
              run: yarn install --immutable --immutable-cache

            - name: Build
              run: yarn run build

            - name: Test
              run: cd packages/platform-sdk-cryptocompare/ && yarn run test --coverage

    eos:
        needs: [conflicts]

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install
              run: yarn install --immutable --immutable-cache

            - name: Build
              run: yarn run build

            - name: Test
              run: cd packages/platform-sdk-eos/ && yarn run test --coverage

    eth:
        needs: [conflicts]

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install
              run: yarn install --immutable --immutable-cache

            - name: Build
              run: yarn run build

            - name: Test
              run: cd packages/platform-sdk-eth/ && yarn run test --coverage

    http-axios:
        needs: [conflicts]

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install
              run: yarn install --immutable --immutable-cache

            - name: Build
              run: yarn run build

            - name: Test
              run: cd packages/platform-sdk-http-axios/ && yarn run test --coverage

    http-bent:
        needs: [conflicts]

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install
              run: yarn install --immutable --immutable-cache

            - name: Build
              run: yarn run build

            - name: Test
              run: cd packages/platform-sdk-http-bent/ && yarn run test --coverage

    http-got:
        needs: [conflicts]

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install
              run: yarn install --immutable --immutable-cache

            - name: Build
              run: yarn run build

            - name: Test
              run: cd packages/platform-sdk-http-got/ && yarn run test --coverage

    http-ky:
        needs: [conflicts]

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install
              run: yarn install --immutable --immutable-cache

            - name: Build
              run: yarn run build

            - name: Test
              run: cd packages/platform-sdk-http-ky/ && yarn run test --coverage

    http-node-fetch:
        needs: [conflicts]

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install
              run: yarn install --immutable --immutable-cache

            - name: Build
              run: yarn run build

            - name: Test
              run: cd packages/platform-sdk-http-node-fetch/ && yarn run test --coverage

    intl:
        needs: [conflicts]

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install
              run: yarn install --immutable --immutable-cache

            - name: Build
              run: yarn run build

            - name: Test
              run: cd packages/platform-sdk-intl/ && yarn run test --coverage

    lsk:
        needs: [conflicts]

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install
              run: yarn install --immutable --immutable-cache

            - name: Build
              run: yarn run build

            - name: Test
              run: cd packages/platform-sdk-lsk/ && yarn run test --coverage

    markets:
        needs: [conflicts]

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install
              run: yarn install --immutable --immutable-cache

            - name: Build
              run: yarn run build

            - name: Test
              run: cd packages/platform-sdk-markets/ && yarn run test --coverage

    marketsquare:
        needs: [conflicts]

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install
              run: yarn install --immutable --immutable-cache

            - name: Build
              run: yarn run build

            - name: Test
              run: cd packages/platform-sdk-marketsquare/ && yarn run test --coverage

    neo:
        needs: [conflicts]

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install
              run: yarn install --immutable --immutable-cache

            - name: Build
              run: yarn run build

            - name: Test
              run: cd packages/platform-sdk-neo/ && yarn run test --coverage

    news:
        needs: [conflicts]

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install
              run: yarn install --immutable --immutable-cache

            - name: Build
              run: yarn run build

            - name: Test
              run: cd packages/platform-sdk-news/ && yarn run test --coverage

    profiles:
        needs: [conflicts]

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install
              run: yarn install --immutable --immutable-cache

            - name: Build
              run: yarn run build

            - name: Test
              run: cd packages/platform-sdk-profiles/ && yarn run test --coverage

    support:
        needs: [conflicts]

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install
              run: yarn install --immutable --immutable-cache

            - name: Build
              run: yarn run build

            - name: Test
              run: cd packages/platform-sdk-support/ && yarn run test --coverage

    trx:
        needs: [conflicts]

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install
              run: yarn install --immutable --immutable-cache

            - name: Build
              run: yarn run build

            - name: Test
              run: cd packages/platform-sdk-trx/ && yarn run test --coverage

    xlm:
        needs: [conflicts]

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install
              run: yarn install --immutable --immutable-cache

            - name: Build
              run: yarn run build

            - name: Test
              run: cd packages/platform-sdk-xlm/ && yarn run test --coverage

    xrp:
        needs: [conflicts]

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install
              run: yarn install --immutable --immutable-cache

            - name: Build
              run: yarn run build

            - name: Test
              run: cd packages/platform-sdk-xrp/ && yarn run test --coverage
