name: Update Dependencies

on:
    schedule:
        - cron: "0 0 * * 0"

jobs:
    unit:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [12.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install
              run: yarn install

            - name: Update Dependencies
              run: bash scripts/deps.sh

            - name: Update yarn.lock
              run: yarn install

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v2
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  title: "chore: update dependencies to latest versions"
