name: Format

on:
    pull_request:
        paths:
            - 'packages/**.ts'

jobs:
    prettier:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1

            - name: Install
              run: yarn install --immutable --immutable-cache

            - name: Run prettier
              run: yarn run prettier --write 'resources/**/*.{css,js,vue}'

            - uses: stefanzweifel/git-auto-commit-action@v4.1.6
              with:
                  commit_message: "style: resolve style guide violations"
                  branch: ${{ github.head_ref }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
